### ISSUE TITLE
Problems when running the pipeline

### ISSUE THREAD

**Issue by iimog** [Robin1em/DTI_Processing_Snakemake#1]
I tried to run the pipeline locally and stumbled over some problems/confusions. I document them here:
- it might be useful to document your own conda environment in a yml file, because the tutorial is constantly updated and that env might not work for this project in the future
- I found it confusing to find the `config.yml` under `additional scripts` (we can generally talk about the directory structure)
- explain the command line parameters (`--cores`, `-p`, `--latency-wait`), why are they required?
- initial error `No module named 'helper_functions'` because `helper_functions` are imported from the Snakefile but located in the `additional scripts` folder
- next error because of naming scheme, I use `BIPN/DRG.BTZ115` for testing and the workflow fails because of the `_2.2` in the filenames. The assumptions on the naming scheme (and generally on the expected content of the origs dir) need to be properly documented or even better properly handled (with some flexibility about the naming and additional non DTI files being ignored)
- next error because `b02b0_4.cnf` file missing. This is expected in the "additional scripts" directory but missing from the repository

I'm stopping here for now. Please fix the issues above and I'll try again.

**Comment by Robin1em** [comment]
Thank you for the feedback! I'll fix these issues.
